# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92614312cfda76afdc14301c07fbc5ef0b3f448a7b03a4c9d6774a71efd653845a7e7fc22c063ba04276cb22b8c5c51e21654733fe29e559b6c224e16e961c5b

test:
  secret_key_base: 3fdc702a847cd41da5607d12a95a4fa694e401bea3ade2dbbb1c34284964db488c30e7b7c3db3410128360a426fa0850446b486a9cf1f6f04459238761ccf07e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
